modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "spruceui"
version = "${version}"
displayName = "ObsidianUI"
displayURL = "https://github.com/ThinkingStudios/SpruceUI-Forge"
credits = "LambdAurora"
authors = "TexTrue, ThinkingStudio"
logoFile = "icon.png"
description = '''
SpruceUI Unofficial Forge port.
Just a GUI library.
'''

[[dependencies.spruceui]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.4,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.spruceui]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"